[project]
name = "monitor-vagas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samuel", email = "samuelvs186@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "playwright>=1.63.0",
    "pydantic>=2.13.5",
    "requests>=2.34.2",
    "streamlit>=1.65.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
monitor-vagas = "monitor_vagas:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
